### PR TITLE
AndroidX dependencies

### PR DESCRIPTION
**Pull request by gaara87**
Given that support libraries are going to come in the form of AndroidX, i've done the heavy lifting process of moving it to over to AndroidX

### CODE REVIEW

**Comment by gaara87** [comment]
@florent37 mind taking a look at it?

**Comment by florent37** [comment]
thanks a lot ! I wanted to do it

**Comment by florent37** [comment]
i will try and publish a new release 👍

**Comment by gaara87** [comment]
thanks for merging it :) apologize since I wasn't able to update it to the newer gradle build and x libs. If you would like me to look into it, I can :)

**Pull request merged**
